// VUE/vuecomunicacioncomponents/src/components/ComicComponent.vue
<template>
    <div>
        <h2>
            {{comic.titulo}}
        </h2>
        <p>{{comic.descripcion}}</p>
        <!-- : nos permite enlazar el obejto -->
        <img :src="comic.imagen"/>
        <h3 :class="{rojo:comic.year <= 2000 , verde:comic.year > 2000}">Año {{comic.year}}</h3>
        <button @click="seleccionarFavorito()">
            Seleccionar favorito
        </button>
        <button class="rojo" @click="eliminarComic()">
            Delete
        </button>
    </div>
</template>

<script>
export default {
    name:"ComicComponent",
    props:["comic","index"],
    methods:{
        seleccionarFavorito(){
            this.$emit("seleccionarFavorito",this.comic);
        },
        eliminarComic(){
            this.$emit("eliminarComic",this.index);
        }
    }
}
</script>

<style>
    @import "./../assets/css/estilocomics.css";
</style>

// ANGULAR/comunicacionangular/src/app/components/comic/comic.component.ts
import { Component, Input, Output , EventEmitter } from '@angular/core';
import { Comic } from 'src/app/models/Comic';
@Component({
  selector: 'app-comic',
  templateUrl: './comic.component.html',
  styleUrls: ['./comic.component.css']
})
export class ComicComponent {
  @Input() comicPropiedad !: Comic;

  @Output() comicSeleccionado: EventEmitter<any> = new EventEmitter();

  @Output() comicEliminado: EventEmitter<any> = new EventEmitter();

  comicFavorito():void{

    this.comicSeleccionado.emit(this.comicPropiedad.titulo);
  }

  comicFuera():void{

    this.comicEliminado.emit(this.comicPropiedad.titulo);
  }

}

<div>
    <h3 style="color: red;">{{comicPropiedad.titulo}}</h3>
    <img src="{{comicPropiedad.imagen}}" style="width: 250px; height: 250px;">
    <h4>Descripcion: {{comicPropiedad.descripcion}}</h4>
    <h4>Año: {{comicPropiedad.year}}</h4>
    <button (click)="comicFavorito()">Seleccionar Favorito</button>
    <button>Modificar</button>
    <button (click)="comicFuera()">Eliminar</button>
</div>
