// VUE/vueservicios/src/components/EmpleadosOficios.vue
<template>
    <div>
        <h1>
            Empleados Oficios
        </h1>
        <table class="table table-bordered">
            <thead>
                <tr>
                    <th>Apellido</th>
                    <th>Oficio</th>
                    <th>Salario</th>
                </tr>
            </thead>
            <tbody>
                <tr v-for="emp in empleados" :key="emp">
                    <td>{{emp.apellido}}</td>
                    <td>{{emp.oficio}}</td>
                    <td>{{emp.salario}}</td>
                </tr>
            </tbody>
        </table>
    </div>
</template>

<script>
    import Global from './../Global';
    import axios from 'axios';
    export default {
        name:"EmpleadosOficios",
        data(){
            return{
                empleados:[]
            }
        },
        methods:{
            loadEmpleados(){
                var oficio = this.$route.params.oficio;
                var request = "api/empleados/empleadosoficio/"+oficio;
                var url = Global.apiEmpleados + request;
                axios.get(url).then(response => {
                    this.empleados = response.data;
                })
            }
        },
        mounted(){
            this.loadEmpleados();
        },
        watch:{
            '$route.params.oficio'(nextVal,oldVal){
                if(nextVal != oldVal){
                    this.loadEmpleados();
                }  
            }
        }
    }
</script>

// REACT/reactservicios/src/components/EmpleadosOficios.js
import axios from 'axios'
import React, { Component } from 'react'
import Global from './Global'

export default class EmpleadosOficios extends Component {

    selectOficio = React.createRef();

    state = {

        oficios : {},

        empleados : {},

        statusOficios : false,

        statusEmpleados : false

    }

    buscarEmpleados = (e) => {

        e.preventDefault();

        var n

    }



    loadOficios = () => {

        var request = "api/Empleados/oficios";

        var url = Global.urlApiEmpleados+request;
        
        console.log(url);

        axios.get(url).then( response => {

            this.setState({

                oficios : response.data ,

                statusOficios : true
            })

        })
        
    }

    componentDidMount = () => {

        this.loadOficios();

    }



    render() {
        return (
        <div>
            <h1>Empleados y Oficios</h1>

            <form>
                <label>Seleccione Oficio: </label>
                <select ref={this.selectOficio}>
                    {
                        this.state.statusOficios == true && 
                        (
                            this.state.oficios.map( (oficio,index) => {
                                return (
                                    <option key={index} value={oficio}>{oficio}</option>
                                )
                            })
                        )
                    }
                </select>
                <button onClick={this.buscarEmpleados}>Buscar Empleados</button>          
            </form>

        </div>
        )
    }
}
