// REACT/reactcrudcoches/src/components/Detalles.js
import React, { Component } from 'react'
import axios from 'axios';
import Global from '../Global';

export default class Detalles extends Component {

    state = {

        coche : [] ,

        status : false
    }

    loadCoche = () => {

        var id = parseInt(this.props.idcoche);

        var request = "/api/Coches/FindCoche/"+id;

        var url = Global.apiCoches + request;

        axios.get(url).then( response => {

            this.setState({

                coche : response.data ,

                status : true
            })
        })
    }

    componentDidMount = () =>{

        this.loadCoche();
    }


  render() {
    return (
      <div>
        <h1>Detalles del coche: {this.props.idcoche}</h1>
        <h4>Id Coche: {this.state.coche.idCoche}</h4>
        <h4>Marca: {this.state.coche.marca}</h4>
        <h4>Modelo: {this.state.coche.modelo}</h4>
        <h4>Conductor: {this.state.coche.conductor}</h4>
        <img src={this.state.coche.imagen} style={{width:"250px" , height:"200px"}}/>
      </div>
    )
  }
}

// VUE/vuecrudcoches/src/components/DetallesComponent.vue
<template>
    <div>
        <h1>Detalles Coche</h1>
        <h2>
            ID Coche: {{coche.idCoche}}
        </h2>
        <h2>
            Coche: {{coche.marca}} {{coche.modelo}}
        </h2>
        <h2>
            Conductor: {{coche.conductor}}
        </h2>
        <img :src="coche.imagen" style="width:300px ; height:300px"/><br/>
        <router-link to="/" class="btn btn-success">Volver</router-link>
    </div>
</template>

<script>
    import ServiceCoches from './../services/ServiceCoches';
    const service = new ServiceCoches();
    export default {
        name:"DetallesComponent",
        data(){
            return{
                coche:{}
            }
        },
        mounted(){
            var id = this.$route.params.id
            service.findCoche(id).then(result => {
                this.coche=result;
                //console.log(this.coche);
            })
        }
    }
</script>
