// REACT/examen30-10-2023/src/components/Menu.js
import React, { Component } from 'react'
import { NavLink } from 'react-router-dom'
import Global from './../Global';
import axios from 'axios';

export default class Menu extends Component {

    state = {

        series : [] ,

        status : false
    }

    loadSeries = () => {

        var request = "api/series";

        var url = Global.apiGeneral + request;

        axios.get(url).then( response => {

            this.setState({

                series : response ,

                status: true
            })
        })
    }

    componentDidMount = () => {

        this.loadSeries();
    }



  render() {
    return (
      <div>
         {/* <!-- Zona NAV --> */}
        <nav className="navbar navbar-expand-lg bg-body-tertiary">
            <div className="container-fluid">
            <NavLink className="navbar-brand" to="#">Stranger Things</NavLink>
            <button className="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
                <span className="navbar-toggler-icon"></span>
            </button>
            <div className="collapse navbar-collapse" id="navbarNavDropdown">
                <ul className="navbar-nav">
                <li className="nav-item">
                    <NavLink className="nav-link active" aria-current="page" to="#">Home</NavLink>
                </li>
                <li className="nav-item">
                    <NavLink className="nav-link" to="#">Nuevo Personaje</NavLink>
                </li>
                <li className="nav-item">
                    <NavLink className="nav-link" to="#">Modificar Personaje</NavLink>
                </li>
                <li className="nav-item dropdown">
                    <NavLink className="nav-link dropdown-toggle" to="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                    Series
                    </NavLink>
                    <ul className="dropdown-menu">
                        {
                           this.state.status == true && 
                           (
                                this.state.series.map( (serie,index) => {

                                    return(
                                        <li>{serie.nombre}</li>
                                    )
                                })
                           )
                        }
                    </ul>
                </li>
                </ul>
            </div>
            </div>
        </nav>
      </div>
    )
  }
}

// VUE/vuecrudcoches/src/components/MenuComponent.vue
<template>
    <div>
        <nav class="navbar navbar-expand-lg bg-body-tertiary">
            <div class="container-fluid">
                <a class="navbar-brand" href="#">CRUD</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <router-link class="nav-link active" aria-current="page" to="/">Home</router-link>
                        </li>
                        <li class="nav-item">
                            <router-link class="nav-link" to="/crear">Crear Coche</router-link>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </div>
</template>

<script>
    export default {
        name:"MenuComponent"
    }
</script>
