// VUE/vuecrudseries/src/components/SeriesComponent.vue
<template>
    <div>
        <h1>Series</h1>
        <div class="card mb-3">
            <div class="card-body">
                <img :src="serie.imagen" class="card-img-top">
                <h5 class="card-title">Titulo: {{serie.nombre}}</h5>
                <h5 class="card-title">Puntuación: {{serie.puntuacion}}</h5>
                <h5 class="card-title">Año: {{serie.anyo}}</h5>
            </div>
        </div>
        <router-link class="btn btn-success" :to="'/personajes/'+ serie.idSerie">Personajes</router-link>
    </div>
</template>

<script>
    import ServiceSeries from './../services/ServiceSeries';
    const service = new ServiceSeries();
    export default {
        name:"SeriesComponent",
        data(){
            return{
                serie:{},
                recibido:false
            }
        },
        methods:{
            findSerie(){
                var id = this.$route.params.id
                service.findSerie(id).then(result => {
                this.serie=result;
                this.recibido=true;
            })
            }
        },
        mounted(){
            this.findSerie();
        },
        watch:{
            '$route.params.id'(nextVal,oldVal){
                if(nextVal != oldVal){
                    this.findSerie();
                }
            }
        }
    }
</script>

// ExamenReactJquery/React/examenreact/src/components/Series.js
import React, { Component } from 'react'
import axios from 'axios'
import { NavLink } from 'react-router-dom'
import Global from '../Global'

export default class Series extends Component {
    state = {

        serie : [] ,

        status : false
    }

    loadSerie = () => {

        var idserie = this.props.idserie;

        var request = "api/series/"+idserie;

        var url = Global.api + request;

        axios.get(url).then(response => {

            this.setState({

                serie : response.data ,

                status: true
            })
        })
    }

    componentDidMount = () => {

        this.loadSerie();
    }

    componentDidUpdate = (oldProps) => {

        if (oldProps.idserie != this.props.idserie){ 

            this.loadSerie();     
        } 
    }


  render() {
    return (
      <div>
                {
                    this.state.status == true && 
                    (
                        <div>
                            <div>
                                <img src={this.state.serie.imagen} style={{width:"250px",height:"250px"}}/>
                            </div>
                            <div>
                                <h4>Nombre: {this.state.serie.nombre}</h4>
                            </div>
                            <div>
                                <h4>Puntuacion: {this.state.serie.puntuacion}</h4>
                            </div>
                            <div>
                                <NavLink to={"/personajes/"+this.props.idserie} className="btn btn-success">Personajes</NavLink>
                            </div>
                        </div>
                    )
                }
      </div>
    )
  }
}
