// VUE/examenvue/src/components/HomeComponent.vue
<template>
    <div>
        <div v-for="cubo in cubos" :key="cubo" class="card" style="width: 18rem;">
            <img :src="cubo.imagen" class="card-img-top">
            <div class="card-body">
                <h5 class="card-title">{{cubo.nombre}}</h5>
                <p class="card-text">Marca : {{cubo.marca}}</p>
                <router-link class="btn btn-success" :to="'/detalles/'+cubo.idCubo">Detalles</router-link>
            </div>
        </div>
    </div>
</template>

<script>
import ServiceTiendas from '@/services/ServiceTienda'
const service = new ServiceTiendas();

export default {
    name:"HomeComponent",
    data(){
        return{
            cubos : []
        }
    },
    methods:{
        loadTodosCubos(){
            service.getTodosCubos().then(response => {
                this.cubos = response;
            })
        }
    },
    mounted(){
        this.loadTodosCubos();
    }
}
</script>

// ANGULAR/examenAngular/src/app/components/home/home.component.ts
import { Component, OnInit } from '@angular/core';
import { ServiceTienda } from 'src/app/services/service.tienda';
import { Cubos } from 'src/app/models/model.cubos';

@Component({
  selector: 'app-home',
  templateUrl: './home.component.html',
  styleUrls: ['./home.component.css']
})
export class HomeComponent implements OnInit {

  public cubos !: Array<Cubos>;

  constructor(
    private _service : ServiceTienda
  ){}

  ngOnInit(): void {
    this.loadCubos();
  }

  loadCubos():void{
    this._service.getTodosCubos().subscribe(response => {
      this.cubos = response;
    })
  }
}

<div *ngIf="cubos">
    <div class="card" style="width: 20%;" *ngFor="let cubo of cubos">
        <img src="{{cubo.imagen}}" class="card-img-top">
        <div class="card-body">
          <h5 class="card-title">{{cubo.nombre}}</h5>
          <p class="card-text">Precio: {{cubo.precio}}</p>
          <p class="card-text">Valoración: {{cubo.valoracion}}</p>
        </div>
        <a class="btn btn-success" [routerLink]="['/detallescubo/'+cubo.idCubo]">Detalles</a>
    </div>
</div>
