// ANGULAR/serviciosangular/src/app/components/coches/coches.component.ts
import { Component, OnInit } from '@angular/core';

//Importamos el enviroment, donde tenemos las apis a consumir
import { environment } from 'src/environments/environment.development';

//Importamos el servicio, donde tenemos todos los metodos.
import { ServiceCoches } from 'src/app/services/service.coches';

//Importamos el modelo, dpnde se encuentra las propiedaes de cada coche y su tipado.
import { Coche } from 'src/app/models/Coche';

@Component({
  selector: 'app-coches',
  templateUrl: './coches.component.html',
  styleUrls: ['./coches.component.css']
})
export class CochesComponent implements OnInit {

  public coches !: Array<Coche>;

  constructor(private _serviceCoches: ServiceCoches){}

  ngOnInit(): void {
    
    this._serviceCoches.getCoches().subscribe(response => {
      this.coches = response;
    })
  }
}

<div>
    <h1>Coches</h1>
    <table class="table">
        <thead>
            <tr>
                <th>Coche</th>
                <th>Conductor</th>
                <th>Imagen</th>
            </tr>
        </thead>
        <tbody>
            <tr *ngFor="let coche of coches">
                <td>{{coche.marca}} {{coche.modelo}}</td>
                <td>{{coche.conductor}}</td>
                <td><img src="{{coche.imagen}}" style="width: 250px; height: 250px;"></td>
            </tr>
        </tbody>
    </table>
</div>

// VUE/vueservicios/src/components/CochesComponent.vue
<template>
    <div>
        <h1>Coches Component y Servicios</h1>
        <table border="1">
            <thead>
                <tr>
                    <th>Coche</th>
                    <th>Conductor</th>
                    <th>Imagen</th>
                </tr>
            </thead>
            <tbody v-for="car in coches" :key="car">
                <tr>
                    <td>{{car.marca}}  {{car.modelo}}</td>
                    <td>{{car.conductor}}</td>
                    <td><img :src="car.imagen" style="width:150px"/></td>
                </tr>
            </tbody>
        </table>
    </div>
</template>

<script>
    import ServiceCoches from './../services/ServiceCoches';
    const service = new ServiceCoches();

    export default {
        name:"CochesComponent",
        data(){
            return{
                coches:[]
            }
        },
        mounted(){
            service.getCoches().then(result => {
                this.coches = result;
            })
        }
    }
</script>
