// ANGULAR/serviciosangular/src/app/components/comic/comic.component.ts
import { Component, Input, Output, EventEmitter } from '@angular/core';
import { Comic } from 'src/app/models/Comic';
@Component({
  selector: 'app-comic',
  templateUrl: './comic.component.html',
  styleUrls: ['./comic.component.css']
})
export class ComicComponent {

  @Input() comic !: Comic;

  @Input() index !: number;

  @Output() seleccionarFavorito: EventEmitter<any> = new EventEmitter();

  @Output() eliminarComic: EventEmitter<any> = new EventEmitter();

  @Output() modificarComic: EventEmitter<any> = new EventEmitter();

  marcarFavorito():void{

    this.seleccionarFavorito.emit(this.comic);
  }

  deleteCominc():void{

    this.eliminarComic.emit(this.index);
  }

  updateComic():void{

    this.modificarComic.emit(this.index);
  }
}

<div>
    <h1 style="color: red;">{{comic.titulo}}</h1>
    <h3>{{comic.descripcion}}</h3>
    <img src="{{comic.imagen}}" style="width: 250px; height:250px"><br/>
    <button (click)="marcarFavorito()" style="background-color: green;">
        Favorito
    </button> 
    <button (click)="deleteCominc()" style="background-color: red;">
        Delete
    </button>
    <button (click)="updateComic()">
        Modificar
    </button>
</div>

// VUE/vuecomunicacioncomponents/src/components/ComicComponent.vue
<template>
    <div>
        <h2>
            {{comic.titulo}}
        </h2>
        <p>{{comic.descripcion}}</p>
        <!-- : nos permite enlazar el obejto -->
        <img :src="comic.imagen"/>
        <h3 :class="{rojo:comic.year <= 2000 , verde:comic.year > 2000}">Año {{comic.year}}</h3>
        <button @click="seleccionarFavorito()">
            Seleccionar favorito
        </button>
        <button class="rojo" @click="eliminarComic()">
            Delete
        </button>
    </div>
</template>

<script>
export default {
    name:"ComicComponent",
    props:["comic","index"],
    methods:{
        seleccionarFavorito(){
            this.$emit("seleccionarFavorito",this.comic);
        },
        eliminarComic(){
            this.$emit("eliminarComic",this.index);
        }
    }
}
</script>

<style>
    @import "./../assets/css/estilocomics.css";
</style>
